# Generated by Django 5.0.2 on 2024-03-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('publicoObjaetivo', models.CharField(max_length=50)),
                ('plataforma', models.CharField(choices=[('Webtoon', 'Webtoon'), ('Crunchyroll Manga', 'Crunchyroll Manga'), ('Youtube', 'Youtube')], max_length=50)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoVideojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('publicoObjaetivo', models.CharField(max_length=50)),
                ('plataforma', models.CharField(choices=[('Xbox', 'Xbox'), ('Playstation', 'Playstation'), ('Computadora', 'Computadora')], max_length=50)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
